### ISSUE TITLE
Could you please split Parse

### ISSUE THREAD

**Issue by vit1251** [galdor/go-cmdline#1]
I want to use `go-cmdline` in a cascade manner to parse args with command context. For example, you may know that `git` options may change depending command is specified.

Right now `Parse` cut first argument and store in ProgramName could you please re-design and make `SubParse` without cut first argument. It takes possibly make cascade parsing.

```
func (c *CmdLine) Parse(args []string) {
	if len(args) == 0 {
		c.Die("empty argument array")
	}

	c.ProgramName = args[0]
	args = args[1:]

	for len(args) > 0 {
	...
```

I mean that you may create
```
func (c *CmdLine) Parse(args []string) {
    ... original code to remove ProgramName ...
    c.ParseSub(args[1:])
}

func (c *CmdLine) ParseSub(args []string) {
    ... original code without ProgramName ...
}
```

That approach provides model parsing arguments with context.

**Comment by galdor** [comment]
I have this problem with subcommands on a regular basis with go-cmdline, and I'm used to manually concatenate program name and arguments. I just added `(*CmdLine).CommandNameAndArguments()` which does just that, and updated `example/commands.go`. I'm not a big fan of the name, but at least it's clear.

I also tagged a new released with a few other patches.

Let me know how it works for you :)
