### ISSUE TITLE
Subcommand & --version

### ISSUE THREAD

**Issue by runeimp** [galdor/go-cmdline#2]
I was playing with this library and found that I could not have subcommands and a flag. The flag in question would be `-v, --version` as common option for many programs. I see in the code there is an exception handling this for `-h, --help` but there is no way to add to this exception list. Maybe something along the lines of:

```go
cl.AddFlag("v", "version", "display version info")
cl.CommandException("v")
```

or

```go
cl.AddFlag("v", "version", "display version info")
cl.ShortCircuit("v", "MyApp v1.0.0")
```

if the flag is to be part of the exception list and also kill further processing and output it's info if it is present on the command line. The way that `-h, --help` work currently.

**Comment by galdor** [comment]
Do you have a full minimal program reproducing the issue ? I regularly use flags and sub-commands without any problem, but I may have missed something.
